name: Odoo CI/CD

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

# ---------------------------
# LINT
# ---------------------------
jobs:
  # lint:
  #   name: Lint Odoo Addons
  #   runs-on: ubuntu-latest
  #   continue-on-error: true

  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: make lint-pylint

  build:
    name: Build & Push Docker Image to ECR
    runs-on: ubuntu-latest
    environment: prod
    # needs: lint

    # strategy:
    #   matrix:
    #     env: [dev, stg, prod]

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF_NAME}_${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t ${{ github.event.repository.name }}:${TAG} .

      - name: Tag & push image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          # IMAGE_URI="$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ github.event.repository.name }}:${TAG}"
          IMAGE_URI="$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/sanne-odoo-web:${TAG}"

          docker tag ${{ github.event.repository.name }}:${TAG} ${IMAGE_URI}
          docker push ${IMAGE_URI}


  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build
    environment: prod

    # strategy:
    #   matrix:
    #     env: [dev, stg, prod]

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Deploy ECS service
        env:
          ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
          ECS_SERVICE: ${{ vars.ECS_SERVICE }}
          TASK_FAMILY: ${{ vars.ECS_TASK_DEFINITION }}
          ODOO_INIT_MODULES: ${{ vars.ODOO_INIT_MODULES }}
          ODOO_UPDATE_MODULES: ${{ vars.ODOO_UPDATE_MODULES }}
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          # IMAGE="$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ github.event.repository.name }}:${TAG}"
          IMAGE="$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/sanne-odoo-web:${TAG}"

          TASK=$(aws ecs describe-task-definition \
            --task-definition "$TASK_FAMILY" \
            --query 'taskDefinition')

          NEW_TASK=$(echo "$TASK" | jq \
            --arg IMAGE "$IMAGE" \
            '.containerDefinitions[0].image = $IMAGE
             | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')

          aws ecs register-task-definition \
            --cli-input-json "$NEW_TASK"

          aws ecs update-service \
            --cluster "$ECS_CLUSTER" \
            --service "$ECS_SERVICE" \
            --task-definition "$TASK_FAMILY"