name: Odoo CI/CD

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

# ---------------------------
# LINT
# ---------------------------
jobs:
  # lint:
  #   name: Lint Odoo Addons
  #   runs-on: ubuntu-latest
  #   continue-on-error: true

  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: make lint-pylint

# ---------------------------
# BUILD & PUSH
# ---------------------------
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    environment: prod
    # needs: lint

    # strategy:
    #   matrix:
    #     env: [dev, stg, prod]

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF_NAME}_${GITHUB_SHA::8}" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: make build-image

      - name: Tag & push image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          # IMAGE_URI="$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${{ github.event.repository.name }}:${TAG}"
          IMAGE_URI="$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/sanne-odoo-web:${TAG}"

          docker tag ${IMAGE_URI} ${IMAGE_URI}
          docker push ${IMAGE_URI}
